name: Nathan Gabriel Art
favicon: null
layout_spectrum: 0.36734
typography_spectrum: 0.3592544982675463
title: Nathan Gabriel Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#130907'
    - '#555354'
    - '#a69359'
    - '#fed468'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
