name: Nathan Gabriel Art
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3592544982675463
title: Nathan Gabriel Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8590ae'
    - '#0d1021'
    - '#536281'
    - '#2a3548'
    - '#a4bbee'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.71451854868792
purpose: []
